version: '3'
services:
  api:
    build: ./MONKEY
    container_name: berry-api
    restart: always
    ports:
      - 80:80
    networks:
      - berry-network
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=berry_user
      - POSTGRES_DB=berry_db
    networks:
      - berry-network
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
networks:
  berry-network:
    driver: bridge
